"""
pdf/sanitizer.py
────────────────
Escapes LaTeX special characters in any user- or AI-generated string.

Characters that must be escaped (and their LaTeX equivalents):
  &  →  \\&
  %  →  \\%
  $  →  \\$
  #  →  \\#
  _  →  \\_
  {  →  \\{
  }  →  \\}
  ~  →  \\textasciitilde{}
  ^  →  \\textasciicircum{}
  \\  →  \\textbackslash{}

Implementation note
───────────────────
A *single-pass* ``re.sub`` is used so that replacement strings are never
re-scanned by subsequent rules.  A naive sequential ``str.replace`` approach
would double-escape the ``{`` and ``}`` braces introduced by, e.g.,
``\\textbackslash{}``.
"""

import re
import html
from typing import Union


# Maps each special character to its LaTeX escape sequence.
_CHAR_MAP: dict[str, str] = {
    "\\":  r"\textbackslash{}",
    "&":   r"\&",
    "%":   r"\%",
    "$":   r"\$",
    "#":   r"\#",
    "_":   r"\_",
    "{":   r"\{",
    "}":   r"\}",
    "~":   r"\textasciitilde{}",
    "^":   r"\textasciicircum{}",
}

# Compile once at import time — order doesn't matter because re.sub is
# single-pass: every input character is matched at most once.
_ESCAPE_RE = re.compile(
    "[" + re.escape("".join(_CHAR_MAP.keys())) + "]"
)


def _replace_char(match: re.Match) -> str:  # type: ignore[type-arg]
    return _CHAR_MAP[match.group(0)]


def sanitize(text: Union[str, None]) -> str:
    """
    Escape all LaTeX special characters in *text*.

    Uses a single-pass regex substitution to prevent double-escaping.
    Additionally, converts Markdown and HTML rich text tags to LaTeX formatting.

    Args:
        text: Raw string from user / AI output.

    Returns:
        LaTeX-safe string, or an empty string when *text* is None / empty.
    """
    if not text:
        return ""
        
    # Unescape HTML entities (e.g. &amp; -> &)
    text_str = html.unescape(str(text))
    # Replace non-breaking spaces with regular spaces to avoid LaTeX unicode errors
    text_str = text_str.replace('\xa0', ' ')
        
    safe_text = _ESCAPE_RE.sub(_replace_char, text_str)
    
    # Convert markdown double-asterisk to LaTeX bold
    safe_text = re.sub(r'\*\*(.*?)\*\*', r'\\textbf{\1}', safe_text)
    
    # Convert HTML tags generated by TipTap
    # Bold
    safe_text = re.sub(r'<(b|strong)>(.*?)</\1>', r'\\textbf{\2}', safe_text, flags=re.IGNORECASE | re.DOTALL)
    # Italic
    safe_text = re.sub(r'<(i|em)>(.*?)</\1>', r'\\textit{\2}', safe_text, flags=re.IGNORECASE | re.DOTALL)
    # Underline
    safe_text = re.sub(r'<u>(.*?)</u>', r'\\underline{\1}', safe_text, flags=re.IGNORECASE | re.DOTALL)
    
    # Clean up paragraph and break tags
    safe_text = re.sub(r'</?p[^>]*>', '', safe_text, flags=re.IGNORECASE)
    safe_text = re.sub(r'<br\s*/?>', ' ', safe_text, flags=re.IGNORECASE)
    
    # Strip any remaining HTML tags (e.g. ul, li)
    safe_text = re.sub(r'<[^>]+>', '', safe_text)
    
    return safe_text


def sanitize_bullet_list(items: list[str]) -> str:
    r"""
    Convert a list of plain-text strings into LaTeX ``\item`` lines.

    Each item is individually sanitized before wrapping.
    Strips leading bullet characters like -, *, • to prevent double-bulleting in LaTeX.
    """
    if not items:
        return r"\item No experience points provided."

    lines = []
    for item in items:
        cleaned = item.strip()
        # Remove leading bullet points, hyphens, and whitespace
        cleaned = re.sub(r'^[\s•\-*]+', '', cleaned).strip()
        if cleaned:
            lines.append(rf"\item {sanitize(cleaned)}")
            
    return "\n".join(lines)

