"""Add email to user_profiles

Revision ID: 4b76e94e041d
Revises: 152e9a6ff208
Create Date: 2026-04-28 02:22:15.820805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b76e94e041d'
down_revision: Union[str, Sequence[str], None] = '152e9a6ff208'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'email')
    # ### end Alembic commands ###
